# .github/workflows/example-2.yml

name: Manual Inputs
on:
    workflow_dispatch:
        inputs:
            FASTLANE_SESSION:
                description: FASTLANE_SESSION
                required: true
jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: echo $GITHUB_TOKEN
