# .github/workflows/example-2.yml

name: Manual Inputs
on:
    workflow_dispatch:
        inputs:
            FASTLANE_SESSION:
                required: true
jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm version patch
            - run: echo $GITHUB_REF
            - run: git push origin $GITHUB_REF
