# .github/workflows/example-2.yml

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: tj-actions/branch-names@v6
              id: branch-name
            - run: ./sachen.sh
              env: 
                BRANCH_NAME: ${{ steps.branch-name.outputs.current_branch }}
                COMMIT: ${{ github.event.pull_request.head.sha }}