# .github/workflows/example-2.yml

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest

        steps:
            - run: echo $GIT_BRANCH
            - run: echo ${{ github.head_ref || github.run_id }}
