# .github/workflows/example-2.yml

name: tests
on: workflow_dispatch

jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo $BRANCH_NAME 
                env: 
                    BRANCH_NAME: ${GITHUB_REF#refs/heads/}

