# .github/workflows/example-2.yml

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest

        concurrency: 
            group: m1-${{ github.head_ref || github.run_id }}
            cancel-in-progress: true

        steps:
            - run: echo ${{ github.head_ref || github.run_id }}
            - run: sleep 200
