# .github/workflows/example-2.yml

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest
        steps:
            - run: touch lol.txt
            - name: upload android apks
              uses: actions/upload-artifact@v2
              with:
                  name: "android-test-apks-${{ github.sha }}"
                  path: ./lol.txt
                  retention-days: 1
