# .github/workflows/example-2.yml

name: tests
on: workflow_dispatch

jobs:
    bump-version:
        name: Bump Package Version
        runs-on: ubuntu-latest
        steps:
            run: "android-test-apks-${GITHUB_SHA}"

